//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTIXMovie.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataTransaksi", Namespace="http://schemas.datacontract.org/2004/07/ServiceTIXMovie")]
    [System.SerializableAttribute()]
    public partial class DataTransaksi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTransaksiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BioskopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TanggalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JamTayangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTransaksi {
            get {
                return this.IDTransaksiField;
            }
            set {
                if ((this.IDTransaksiField.Equals(value) != true)) {
                    this.IDTransaksiField = value;
                    this.RaisePropertyChanged("IDTransaksi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Film {
            get {
                return this.FilmField;
            }
            set {
                if ((this.FilmField.Equals(value) != true)) {
                    this.FilmField = value;
                    this.RaisePropertyChanged("Film");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Bioskop {
            get {
                return this.BioskopField;
            }
            set {
                if ((object.ReferenceEquals(this.BioskopField, value) != true)) {
                    this.BioskopField = value;
                    this.RaisePropertyChanged("Bioskop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string NamaCustomer {
            get {
                return this.NamaCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaCustomerField, value) != true)) {
                    this.NamaCustomerField = value;
                    this.RaisePropertyChanged("NamaCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Studio {
            get {
                return this.StudioField;
            }
            set {
                if ((this.StudioField.Equals(value) != true)) {
                    this.StudioField = value;
                    this.RaisePropertyChanged("Studio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Tanggal {
            get {
                return this.TanggalField;
            }
            set {
                if ((object.ReferenceEquals(this.TanggalField, value) != true)) {
                    this.TanggalField = value;
                    this.RaisePropertyChanged("Tanggal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string JamTayang {
            get {
                return this.JamTayangField;
            }
            set {
                if ((object.ReferenceEquals(this.JamTayangField, value) != true)) {
                    this.JamTayangField = value;
                    this.RaisePropertyChanged("JamTayang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Row {
            get {
                return this.RowField;
            }
            set {
                if ((object.ReferenceEquals(this.RowField, value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Seat {
            get {
                return this.SeatField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatField, value) != true)) {
                    this.SeatField = value;
                    this.RaisePropertyChanged("Seat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Harga {
            get {
                return this.HargaField;
            }
            set {
                if ((object.ReferenceEquals(this.HargaField, value) != true)) {
                    this.HargaField = value;
                    this.RaisePropertyChanged("Harga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Total {
            get {
                return this.TotalField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalField, value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataFilm", Namespace="http://schemas.datacontract.org/2004/07/ServiceTIXMovie")]
    [System.SerializableAttribute()]
    public partial class DataFilm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JudulFilmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeskripsiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HargaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string JudulFilm {
            get {
                return this.JudulFilmField;
            }
            set {
                if ((object.ReferenceEquals(this.JudulFilmField, value) != true)) {
                    this.JudulFilmField = value;
                    this.RaisePropertyChanged("JudulFilm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Deskripsi {
            get {
                return this.DeskripsiField;
            }
            set {
                if ((object.ReferenceEquals(this.DeskripsiField, value) != true)) {
                    this.DeskripsiField = value;
                    this.RaisePropertyChanged("Deskripsi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Harga {
            get {
                return this.HargaField;
            }
            set {
                if ((object.ReferenceEquals(this.HargaField, value) != true)) {
                    this.HargaField = value;
                    this.RaisePropertyChanged("Harga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusTiket", Namespace="http://schemas.datacontract.org/2004/07/ServiceTIXMovie")]
    [System.SerializableAttribute()]
    public partial class StatusTiket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDTransaksiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDStatus {
            get {
                return this.IDStatusField;
            }
            set {
                if ((this.IDStatusField.Equals(value) != true)) {
                    this.IDStatusField = value;
                    this.RaisePropertyChanged("IDStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDTransaksi {
            get {
                return this.IDTransaksiField;
            }
            set {
                if ((object.ReferenceEquals(this.IDTransaksiField, value) != true)) {
                    this.IDTransaksiField = value;
                    this.RaisePropertyChanged("IDTransaksi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataRegister", Namespace="http://schemas.datacontract.org/2004/07/ServiceTIXMovie")]
    [System.SerializableAttribute()]
    public partial class DataRegister : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transaksitiket", ReplyAction="http://tempuri.org/IService1/transaksitiketResponse")]
        string transaksitiket(int IDFilm, string Bioskop, string NamaCustomer, string Phone, int Studio, string Tanggal, string JamTayang, string Row, string Seat, string Harga, string Total, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transaksitiket", ReplyAction="http://tempuri.org/IService1/transaksitiketResponse")]
        System.Threading.Tasks.Task<string> transaksitiketAsync(int IDFilm, string Bioskop, string NamaCustomer, string Phone, int Studio, string Tanggal, string JamTayang, string Row, string Seat, string Harga, string Total, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edittransaksitiket", ReplyAction="http://tempuri.org/IService1/edittransaksitiketResponse")]
        string edittransaksitiket(string IDTransaksi, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edittransaksitiket", ReplyAction="http://tempuri.org/IService1/edittransaksitiketResponse")]
        System.Threading.Tasks.Task<string> edittransaksitiketAsync(string IDTransaksi, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletetransaksitiket", ReplyAction="http://tempuri.org/IService1/deletetransaksitiketResponse")]
        string deletetransaksitiket(string NamaCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletetransaksitiket", ReplyAction="http://tempuri.org/IService1/deletetransaksitiketResponse")]
        System.Threading.Tasks.Task<string> deletetransaksitiketAsync(string NamaCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/film", ReplyAction="http://tempuri.org/IService1/filmResponse")]
        string film(string JudulFilm, string Deskripsi, string Harga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/film", ReplyAction="http://tempuri.org/IService1/filmResponse")]
        System.Threading.Tasks.Task<string> filmAsync(string JudulFilm, string Deskripsi, string Harga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editfilm", ReplyAction="http://tempuri.org/IService1/editfilmResponse")]
        string editfilm(int id, string Harga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editfilm", ReplyAction="http://tempuri.org/IService1/editfilmResponse")]
        System.Threading.Tasks.Task<string> editfilmAsync(int id, string Harga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletefilm", ReplyAction="http://tempuri.org/IService1/deletefilmResponse")]
        string deletefilm(string JudulFilm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletefilm", ReplyAction="http://tempuri.org/IService1/deletefilmResponse")]
        System.Threading.Tasks.Task<string> deletefilmAsync(string JudulFilm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/statustiket", ReplyAction="http://tempuri.org/IService1/statustiketResponse")]
        string statustiket(int IDStatus, string IDTransaksi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/statustiket", ReplyAction="http://tempuri.org/IService1/statustiketResponse")]
        System.Threading.Tasks.Task<string> statustiketAsync(int IDStatus, string IDTransaksi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataTransaksi", ReplyAction="http://tempuri.org/IService1/DataTransaksiResponse")]
        ClientTIXMovie.ServiceReference1.DataTransaksi[] DataTransaksi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataTransaksi", ReplyAction="http://tempuri.org/IService1/DataTransaksiResponse")]
        System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.DataTransaksi[]> DataTransaksiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataFilm", ReplyAction="http://tempuri.org/IService1/DataFilmResponse")]
        ClientTIXMovie.ServiceReference1.DataFilm[] DataFilm();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataFilm", ReplyAction="http://tempuri.org/IService1/DataFilmResponse")]
        System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.DataFilm[]> DataFilmAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (StatusTiket) of message StatusTiketRequest does not match the default value (StatusTiket1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StatusTiket", ReplyAction="http://tempuri.org/IService1/StatusTiketResponse")]
        ClientTIXMovie.ServiceReference1.StatusTiketResponse StatusTiket1(ClientTIXMovie.ServiceReference1.StatusTiketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StatusTiket", ReplyAction="http://tempuri.org/IService1/StatusTiketResponse")]
        System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.StatusTiketResponse> StatusTiket1Async(ClientTIXMovie.ServiceReference1.StatusTiketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        string Register(string username, string email, string phone, string password, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string username, string email, string phone, string password, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataRegist", ReplyAction="http://tempuri.org/IService1/DataRegistResponse")]
        ClientTIXMovie.ServiceReference1.DataRegister[] DataRegist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataRegist", ReplyAction="http://tempuri.org/IService1/DataRegistResponse")]
        System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.DataRegister[]> DataRegistAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusTiket", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StatusTiketRequest {
        
        public StatusTiketRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusTiketResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StatusTiketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientTIXMovie.ServiceReference1.StatusTiket[] StatusTiketResult;
        
        public StatusTiketResponse() {
        }
        
        public StatusTiketResponse(ClientTIXMovie.ServiceReference1.StatusTiket[] StatusTiketResult) {
            this.StatusTiketResult = StatusTiketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientTIXMovie.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientTIXMovie.ServiceReference1.IService1>, ClientTIXMovie.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string transaksitiket(int IDFilm, string Bioskop, string NamaCustomer, string Phone, int Studio, string Tanggal, string JamTayang, string Row, string Seat, string Harga, string Total, string Status) {
            return base.Channel.transaksitiket(IDFilm, Bioskop, NamaCustomer, Phone, Studio, Tanggal, JamTayang, Row, Seat, Harga, Total, Status);
        }
        
        public System.Threading.Tasks.Task<string> transaksitiketAsync(int IDFilm, string Bioskop, string NamaCustomer, string Phone, int Studio, string Tanggal, string JamTayang, string Row, string Seat, string Harga, string Total, string Status) {
            return base.Channel.transaksitiketAsync(IDFilm, Bioskop, NamaCustomer, Phone, Studio, Tanggal, JamTayang, Row, Seat, Harga, Total, Status);
        }
        
        public string edittransaksitiket(string IDTransaksi, string Status) {
            return base.Channel.edittransaksitiket(IDTransaksi, Status);
        }
        
        public System.Threading.Tasks.Task<string> edittransaksitiketAsync(string IDTransaksi, string Status) {
            return base.Channel.edittransaksitiketAsync(IDTransaksi, Status);
        }
        
        public string deletetransaksitiket(string NamaCustomer) {
            return base.Channel.deletetransaksitiket(NamaCustomer);
        }
        
        public System.Threading.Tasks.Task<string> deletetransaksitiketAsync(string NamaCustomer) {
            return base.Channel.deletetransaksitiketAsync(NamaCustomer);
        }
        
        public string film(string JudulFilm, string Deskripsi, string Harga) {
            return base.Channel.film(JudulFilm, Deskripsi, Harga);
        }
        
        public System.Threading.Tasks.Task<string> filmAsync(string JudulFilm, string Deskripsi, string Harga) {
            return base.Channel.filmAsync(JudulFilm, Deskripsi, Harga);
        }
        
        public string editfilm(int id, string Harga) {
            return base.Channel.editfilm(id, Harga);
        }
        
        public System.Threading.Tasks.Task<string> editfilmAsync(int id, string Harga) {
            return base.Channel.editfilmAsync(id, Harga);
        }
        
        public string deletefilm(string JudulFilm) {
            return base.Channel.deletefilm(JudulFilm);
        }
        
        public System.Threading.Tasks.Task<string> deletefilmAsync(string JudulFilm) {
            return base.Channel.deletefilmAsync(JudulFilm);
        }
        
        public string statustiket(int IDStatus, string IDTransaksi) {
            return base.Channel.statustiket(IDStatus, IDTransaksi);
        }
        
        public System.Threading.Tasks.Task<string> statustiketAsync(int IDStatus, string IDTransaksi) {
            return base.Channel.statustiketAsync(IDStatus, IDTransaksi);
        }
        
        public ClientTIXMovie.ServiceReference1.DataTransaksi[] DataTransaksi() {
            return base.Channel.DataTransaksi();
        }
        
        public System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.DataTransaksi[]> DataTransaksiAsync() {
            return base.Channel.DataTransaksiAsync();
        }
        
        public ClientTIXMovie.ServiceReference1.DataFilm[] DataFilm() {
            return base.Channel.DataFilm();
        }
        
        public System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.DataFilm[]> DataFilmAsync() {
            return base.Channel.DataFilmAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTIXMovie.ServiceReference1.StatusTiketResponse ClientTIXMovie.ServiceReference1.IService1.StatusTiket1(ClientTIXMovie.ServiceReference1.StatusTiketRequest request) {
            return base.Channel.StatusTiket1(request);
        }
        
        public ClientTIXMovie.ServiceReference1.StatusTiket[] StatusTiket1() {
            ClientTIXMovie.ServiceReference1.StatusTiketRequest inValue = new ClientTIXMovie.ServiceReference1.StatusTiketRequest();
            ClientTIXMovie.ServiceReference1.StatusTiketResponse retVal = ((ClientTIXMovie.ServiceReference1.IService1)(this)).StatusTiket1(inValue);
            return retVal.StatusTiketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.StatusTiketResponse> ClientTIXMovie.ServiceReference1.IService1.StatusTiket1Async(ClientTIXMovie.ServiceReference1.StatusTiketRequest request) {
            return base.Channel.StatusTiket1Async(request);
        }
        
        public System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.StatusTiketResponse> StatusTiket1Async() {
            ClientTIXMovie.ServiceReference1.StatusTiketRequest inValue = new ClientTIXMovie.ServiceReference1.StatusTiketRequest();
            return ((ClientTIXMovie.ServiceReference1.IService1)(this)).StatusTiket1Async(inValue);
        }
        
        public string Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public string Register(string username, string email, string phone, string password, string role) {
            return base.Channel.Register(username, email, phone, password, role);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string username, string email, string phone, string password, string role) {
            return base.Channel.RegisterAsync(username, email, phone, password, role);
        }
        
        public ClientTIXMovie.ServiceReference1.DataRegister[] DataRegist() {
            return base.Channel.DataRegist();
        }
        
        public System.Threading.Tasks.Task<ClientTIXMovie.ServiceReference1.DataRegister[]> DataRegistAsync() {
            return base.Channel.DataRegistAsync();
        }

        internal object edittransaksitiket(int iDTransaksi, string status)
        {
            throw new NotImplementedException();
        }
    }
}
